export {default as Home} from './Home'
export {default as Blog} from './Blog'
export {default as Video} from './Video'
export {default as Contact} from './Contact'
export {default as About} from './About'
export {default as Products} from './Products'